// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxgsamdfdvdeqgtzzojy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94Z3NhbWRmZHZkZXFndHp6b2p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MzcyOTEsImV4cCI6MjA3MzQxMzI5MX0.2D1Ti7bSWAKyccLXB97pPYvYZRr-xZEQtsQPIDRnlzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});