// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iilarpgpmpwmcaxppega.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpbGFycGdwbXB3bWNheHBwZWdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNDc5NTIsImV4cCI6MjA3MTgyMzk1Mn0.hSae2E-uG71jmRZZ7d2jplCGwZNZuidh14nNTFkyDxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});